### ISSUE TITLE
No notification bell when receiving notifications

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/notifications#109]
## What Happened
As title implies

## Expected Behavior
There should be a bell sound when receiving a notification.

## Steps to Reproduce
1. Open terminal.
2. `sleep 5` and go out of focus (just minimise it).
3. Notification is added to list but it doesn't show the notification overlay (?)/popover (?).

`notify-send test` does work.

## Platform Information
eOS 6

**Comment by danrabbit** [comment]
It looks like we're having an issue where child schemas for app notifications are not being created and so the server doesn't send notifications because it can't tell if the app has permission to or not

**Comment by davidmhewitt** [comment]
The schemas are not being created because the path it's trying to create them under is invalid. This is because the desktop_id is not received by the notification server as mentioned in https://github.com/elementary/wingpanel-indicator-notifications/issues/179.

`GLib.Notification` is detecting that the notification portal exists, so sends notifications via that instead of directly to the notification server using the `org.freedesktop.Notification` protocol. GLib doesn't send the desktop ID to the portal, so it never gets sent onto the notifications server.

**Comment by davidmhewitt** [comment]
Ok, I've found this is another side effect of `GTK_USE_PORTAL=1` being set in the environment in https://github.com/elementary/default-settings/pull/204 .

If that's not set, GLib correctly sends notifications via `org.freedesktop.Notification` instead of the portal.
